### ISSUE TITLE
Laravel 9 Issue

### ISSUE THREAD

**Issue by iamB0rgy** [kylemilloy/edamam-php#1]
Hi, 

I am getting this error. 

`PS C:\xampp\htdocs\food> composer require kylemilloy/edamam-php  
Using version ^0.2.2 for kylemilloy/edamam-php
./composer.json has been updated
Running composer update kylemilloy/edamam-php
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires kylemilloy/edamam-php ^0.2.2 -> satisfiable by kylemilloy/edamam-php[0.2.2].
    - kylemilloy/edamam-php 0.2.2 requires guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.5).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require kylemilloy/edamam-php:*" to figure out if any version is installable, or "composer require kylemilloy/edamam-php:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

**Comment by kylemilloy** [comment]
Deps have been updated and ver bumped to v1.0.0. Should be good to go with L9.
